apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stackdriver.addons.sigs.k8s.io
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: addons.sigs.k8s.io
  names:
    kind: Stackdriver
    plural: stackdriver
    singular: stackdriver
    shortNames:
      - sd
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectID:
                  type: string
                clusterName:
                  type: string
                clusterLocation:
                  type: string
                enableStackdriverForApplications:
                  type: boolean
                optimizedMetrics:
                  type: boolean
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer